# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[á…](bold green)"     # The "success_symbol" segment is being set to "á…" with the color "bold green"
error_symbol = "[âœ–](bold red)"         # The "error_symbol" segment is being set to "âœ—" with the color "bold red"

[directory]
read_only = " ğŸ”’"

[shlvl]
disabled = false
threshold = 3

[status]
disabled = false
format = "[\\($status\\) ]($style)"
